// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoenmakerBal.Api.Data;

#nullable disable

namespace SchoenmakerBal.Api.Migrations
{
    [DbContext(typeof(SchoenmakerBalDbContext))]
    [Migration("20220528102336_ImageFix")]
    partial class ImageFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SchoenmakerBal.Api.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("SchoenmakerBal.Api.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SchoenmakerBal.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Een grote 400 ml spuitbus voor het waterdicht maken. Geschikt voor alle soorten leder en suède.Voor schoenen,tassen en kleding.Uitsluitend op goed geventileerde plaatsen te gebruiken",
                            ImageURL = "/Images/Onderhoudsmiddel/AntiRain.jpg",
                            Name = "ANTI RAIN PROTECTOR 400 ML",
                            Price = 7.18m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Bama herstellende olie voor gevet leer. Voedt, beschermt en verzorgt. De herstellende olie trekt diep in de schoen om het materiaal zacht en soepel te houden. GEBRUIKSAANWIJZING -Stof en vuil verwijderen van oppervlakte -Schud de spray voor gebruik -Spuit gelijkmatig vanaf een afstand van 20 cm rond het materiaal doornat te maken -10 minuten laten drogen  Geschikt voor alle kleuren gewaxed-, geolied leer/nubuck.",
                            ImageURL = "/Images/Onderhoudsmiddel/BamaOil.png",
                            Name = "BAMA S20 RENOVATING OIL 250 ML",
                            Price = 8.23m,
                            Qty = 45
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Collonil Waxleather beschermt, verzorgt en voedt gewaxte- en matte leersoorten. Met bijenwas. Geschikt voor o.a. analine, nappa en pull up leer. Ook te gebruiken bij Hightech materialen.",
                            ImageURL = "/Images/Onderhoudsmiddel/CollonilWax.png",
                            Name = "COLLONIL WAXLEATHER 200 ML",
                            Price = 9.93m,
                            Qty = 30
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Ledercrème is een product om leder regelmatig te onderhouden. Trekt goed in de poriën van het leder en houd het soepel. Conserveert het leder en is te gebruiken op meubelen,schoenen, tassen, jassen, zadels, hoofdstellen, etc. Gebruiksaanwijzing: Met een doekje of sponsje goed inwrijven, enige tijd laten intrekken en zonodig uitwrijven. Bij regelmatig gebruik blijft het leder soepel en waterafstotend. Verlengt de levensduur van het leder.",
                            ImageURL = "/Images/Onderhoudsmiddel/RapideLeathergel.png",
                            Name = "RAPIDE GEL TUBE 200 ML",
                            Price = 13.62m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Rapide witte vaseline is een op zeer hoogwaardig geraffineerd product van farmaceutische kwaliteit. Het bezit een hoge mate aan zuiverheid en is ideaal om te gebruiken voor vele onderhoudsdoeleinden. GEBRUIKSAANWIJZING: Wrijf een beetje vaseline op het te behandelen product voor een perfect onderhoud.",
                            ImageURL = "/Images/Onderhoudsmiddel/RapideVaseline.png",
                            Name = "RAPIDE VASELINE 150 ML",
                            Price = 8.34m,
                            Qty = 85
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "U-Lace veters zijn er niet alleen om je sneakers te persionaliseren, maar bieden ook een uitkomst voor iedereen die moeite heeft met het strikken van veters. Doordat U-Laces elastisch zijn kunt u van een normale veterschoen een instapper maken. Blister met 6 losse stukjes in één kleur.",
                            ImageURL = "/Images/Schoenveters/Ulace.png",
                            Name = "ULACES MIX & MATCH",
                            Price = 4.95m,
                            Qty = 120
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Echte leren veters 120 cm in de kleuren: Beige, middelbruin, donkerbruin, wit, zwart, cognac en geel/bruin. Bestellen per 12 of 25 paar per kleur.",
                            ImageURL = "/Images/Schoenveters/LerenVeters.png",
                            Name = "LEREN VETER",
                            Price = 4.99m,
                            Qty = 200
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Echte leren veters op rol.",
                            ImageURL = "/Images/Schoenveters/LerenVeterRol.png",
                            Name = "LEREN VETER SBT 25 METER",
                            Price = 38.99m,
                            Qty = 300
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Marla veters in rode blister.",
                            ImageURL = "/Images/Schoenveters/VetersElastisch.png",
                            Name = "MARLA ELASTISCH 75 CM",
                            Price = 3.99m,
                            Qty = 20
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Marla veters in rode blister.",
                            ImageURL = "/Images/Schoenveters/VetersZwart.png",
                            Name = "MARLA BRANDWEREND 120 CM ZWART",
                            Price = 3.99m,
                            Qty = 150
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Marla veters in rode blister. De lengte van de veters wordt veranderd van 65 cm. in 60 cm. 60 cm veters worden automatisch geleverd als de 65 cm lengte op is.",
                            ImageURL = "/Images/Schoenveters/VetersPlat.png",
                            Name = "MARLA PLAT 60/65 CM",
                            Price = 4.99m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Sportzool voor hardlopen. 360°-landing cup stabiliseert de hiel na de landing. Heel strike zone zorgt voor extra schokabsorbtie bij de landing. Rebound pad levert duurzame demping. Midfoot support voor extra stabiliteit op rechte wegen. Flex groovers bespaart energie, stap voor stap. Equalize pad verdeelt de druk over de voorvoet. Aerarion holes maken het transport van lucht en vocht mogelijk. Low frictation fabric helpt hitte door wrijving te verminderen.",
                            ImageURL = "/Images/Inlegzolen/BamaInlegzolen.png",
                            Name = "BAMA RUNNING",
                            Price = 18.47m,
                            Qty = 212
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Functionele textielvezel met actieve koolstof op basis van latexschuim. De actieve koolstof absorbeert het voetvocht en voorkomt inaangename geurtjes.  De geperforeerde onderlaag zorgt voor een optimale luchtcirculatie in uw schoenen.  Wordt aanbevolen voor schoenen met Tex membramen.",
                            ImageURL = "/Images/Inlegzolen/Famaco.png",
                            Name = "FAMACO COMFORT & DRY",
                            Price = 6.99m,
                            Qty = 112
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Vergroot Extra warme inlegzool in echt lamsvacht. Zogt er voor dat uw voeten warm blijven en voor een uitstekend draagcomfort. Antislip onderlaag biedt een stevige grip en stabiliteit. Plantaardig gelooid. Natuurlijk product.",
                            ImageURL = "/Images/Inlegzolen/FamacoUltraWarm.png",
                            Name = "FAMACO ULTRA WARM",
                            Price = 12.99m,
                            Qty = 90
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Anti transpiratiezool. Neutraliseert nare luchtjes door actieve koolstof.",
                            ImageURL = "/Images/Inlegzolen/MarlaAntiGeur.png",
                            Name = "MARLA GEURSMULLER",
                            Price = 5.99m,
                            Qty = 95
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Hoge kwaliteit lederen inlegzool, plantaardig gelooid. Latex onderlaag op basis van actieve kool, absorbeert geuren. Comfortabel en hygienisch",
                            ImageURL = "/Images/Inlegzolen/FamacoKids.png",
                            Name = "FAMACO UNIVERSAL ROYAL KIDS",
                            Price = 9.78m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Voorkomt een branderig gevoel onder de bal van de voet en het naar voren glijden",
                            ImageURL = "/Images/Inlegzolen/MarlaGelPads.png",
                            Name = "MARLA GEL PADS",
                            Price = 5.99m,
                            Qty = 73
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Metalen schoenlepel met haak. Per 10 stuks verpakt",
                            ImageURL = "/Images/Borstels_Schoenlepels_Spanners/Haklepel.png",
                            Name = "HAKLEPEL MET HAAK NIKKEL",
                            Price = 5.28m,
                            Qty = 50
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            Description = "Kunststof schoenlepel zonder haak met en zonder opdruk. Per 50 stuks verpakt.",
                            ImageURL = "/Images/Borstels_Schoenlepels_Spanners/Schoenlepel.png",
                            Name = "WEGGEEFSCHOENLEPEL KUNSTSTOF",
                            Price = 3.40m,
                            Qty = 60
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            Description = "Kunststof schoenspanner van Bama.",
                            ImageURL = "/Images/Borstels_Schoenlepels_Spanners/KunstoffSpanner.png",
                            Name = "BAMA SCHOENSPANNER PLASTIC",
                            Price = 9.26m,
                            Qty = 70
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            Description = "Ceder houten schoenspanner.",
                            ImageURL = "/Images/Borstels_Schoenlepels_Spanners/CederSpanner.png",
                            Name = "CEDER SCHOENSPANNER ELEGANCE",
                            Price = 27.80m,
                            Qty = 120
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            Description = "Een uitpoetser van de Bama.",
                            ImageURL = "/Images/Borstels_Schoenlepels_Spanners/BamaUitpoetser.png",
                            Name = "BAMA H07 UITPOETSER",
                            Price = 6.07m,
                            Qty = 100
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "Reinigt en herstelt suède en nubuck.",
                            ImageURL = "/Images/Borstels_Schoenlepels_Spanners/NubuckSponge.png",
                            Name = "MARLA SUEDE & NUBUCK SPONS",
                            Price = 5.13m,
                            Qty = 150
                        });
                });

            modelBuilder.Entity("SchoenmakerBal.Api.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Onderhoudsmiddelen"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SchoenVeters"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Inlegzolen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Borstels, Schoenenlepels, Spanners"
                        });
                });

            modelBuilder.Entity("SchoenmakerBal.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 2,
                            UserName = "Sarah"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
